version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  portal:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://username:password@db:5432/database
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000
      interval: 3m30s
      timeout: 15s
      retries: 10
      start_period: 30s

# vim: set ts=2 sw=2 expandtab:
