version: '3.9'

services:
  portal:
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/src
    ports:
      - 8000:8000
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8000
      interval: 3m30s
      timeout: 15s
      retries: 10
      start_period: 30s
  api:
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/src
    ports:
      - 8001:8000
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8001
      interval: 3m30s
      timeout: 15s
      retries: 10
      start_period: 30s

# vim: set ts=2 sw=2 expandtab:
