version: '3.9'

services:
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
# vim: set ts=2 sw=2 expandtab:
