name: pipeline

on:
  - push
  - pull_request

jobs:
  compliance-python:
    name: compliance-python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: linter and test for python
        run: |
          pip install -r backend/requirements.txt
          pip install flake8
          flake8 backend/
          cd backend && python -m pytest

  compliance-flutter:
    name: compliance-flutter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@v1
      - name: linter and test for flutter
        run: |
          cd frontend && flutter pub get
          cd frontend && flutter test

# vim: set ts=2 sw=2 expandtab:
