name: pipeline

on:
  - push
  - pull_request

jobs:
  compliance:
    name: compliance
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: linter and test for python
        run: |
          pip install -r backend/requirements.txt
          pip install flake8
          flake8 backend/
          cd backend && python -m pytest


# vim: set ts=2 sw=2 expandtab:
